config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'flats/query', to: 'flats#search'
  resources :flats

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  before_action :set_search, except: [:search]

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.create(flat_params)
    redirect_to flat_path(@flat)
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  def search
    @search = search_params
    @flats = Flat.where("name LIKE '%#{@search}%'")
    puts @flats
    render :index
  end

  private

  def set_search
    @search = {query: ""}
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def search_params
    params.require(:query)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="col-xs-12 col-md-4 col-md-offset-4">
  <h3>Create a new flat</h3>
  <%= form_for @flat do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :address %>
      <%= f.text_field :address, class: "form-control" %>
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>
      <%= f.label :price_per_night %>
      <%= f.text_field :price_per_night, class: "form-control" %>
      <%= f.label :number_of_guests %>
      <%= f.text_field :number_of_guests, class: "form-control" %>
      <br>
      <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/flats/edit.html.erb
<%= render "form" %>

app/views/flats/index.html.erb
<h1>All flats</h1>

<div class="wrapper">
  <p>You searched for <%= @search %></p>
  <div class="container">
    <% @flats.each do |flat| %>
    <div class="card">
      <div class="flat-name">
        <%= link_to flat.name, flat_path(flat) %>
      </div>
      <div class="address">
        <%= flat.address %>
      </div>
      <div class="price-and-guests">
        <ul class="list-inline">
          <li>
            <i class="fas fa-users"></i>
            <%= flat.number_of_guests %>
          </li>
          <li>
            <i class="fas fa-euro-sign"></i>
            <%= flat.price_per_night %>
          </li>
        </ul>
      </div>
      <div class="action-list">
        <%= link_to "More info", flat_path(flat) %>
        <%= link_to "Edit", edit_flat_path(flat) %>
        <%= link_to "Destroy", flat_path(flat), method: :delete %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= render "form" %>

app/views/flats/show.html.erb
<div class="wrapper">
  <div class="container-custom">
    <h2> <%= @flat.name %></h2>
    <br>
    <ul class="list-inline">
      <li>
            <i class="fas fa-users"></i>
            <%= @flat.number_of_guests %>
          </li>
          <li>
            <i class="fas fa-euro-sign"></i>
            <%= @flat.price_per_night %>
          </li>
    </ul>
    <p>Address : <%= @flat.address %></p>
    <p> <%= @flat.description %></p>
    <%= link_to "Go back home", flats_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <a href="/flats" class="navbar-wagon-item navbar-wagon-link"><i class="fas fa-home"></i>Simple Airbnb</a>
      <form action="http://localhost:3000/flats/query" method="get">
        <ul class="list-inline">
          <li><input type="text" name="query"></li>

          <li><input type="submit" class="btn btn-blue" value="Search"></li>
        </ul>
      </form>
      <a class="btn-blue" href="/flats/new">Add Flat</a>
    </div>
    <div class="wrapper-white">
      <%= yield %>
    </div>
  </body>
</html>